Check all users
FlavioAandres/Lambdas-WP pull request #47
Opened 2021-05-20 14:35 UTC by FlavioAandres

2021-05-20 14:45 UTC, AndresMorelos requested changes
Some feedbacks given.

2021-05-20 14:45 UTC, AndresMorelos commented on devutils/generateDataCreditoCredentials.js
> +const password = "vfaxynnqedzcoezh";
Delete User and Password

2021-05-20 14:45 UTC, AndresMorelos commented on package.json
> +    "aws-sdk": "^2.910.0",
AWS environment provide by default the AWS-SDK, this package is not necessary in the dependencies sections only in the dev-dependencies to perform tests in local.

2021-05-20 17:28 UTC, AndresMorelos commented
> @AndresMorelos Have you any idea if we can use the google AUTH2 to check and list emails?

@FlavioAandres yes, it is possible, here is a example provided by google https://developers.google.com/gmail/api/quickstart/nodejs

2021-05-22 01:15 UTC, FlavioAandres commented
@AndresMorelos Hey, the scope of this PR is allow to new user to start using the app without issues, butt, I found that each user has their on bank template and if we want to replicate the bank to another account we need to create the same file to be able track the email subject and other filters... 

I want to create only one bank template and relate it into the users collection... in this way we could have an array of BankIds inside the user and only 1 template per bank... 

the other option is create that "same document" of banks for the new users  each time they were signed up and add this change of schemas in another PR :)

thoughts?

2021-05-22 13:16 UTC, AndresMorelos commented
@FlavioAandres The best thing now is create one document per bank and then relate them to the client by id, on this form we will reduce the amount of data in the collection; and with a population of the data by id we can get the banks.


```js
//npm i mongoose-autopopulate

banks: [{
    type: mongoose.Types.ObjectId,
    ref: 'Bank',
    autopopulate: true // Needed by the plugin of autopopulation
}]

userSchema.plugin(require('mongoose-autopopulate')); // this plugin auto populate the info of the Refs
```

Then we can made a update of a user each time that they activate or desactivate a bank removing or adding the ID of the bank.

2021-05-23 03:23 UTC, FlavioAandres commented
🤘

2021-05-23 13:26 UTC, FlavioAandres commented
@AndresMorelos This is ready 🚀  
Deployed on my site, please go ahead merging when you deploy your changes, just to know nothing is failing :D

2021-05-24 19:52 UTC, merged